<Directory @ap_docroot@/@name@>
  Options FollowSymLinks
  AllowOverride None
  <IfModule mod_php5.c>
    php_admin_flag register_globals off
    php_admin_flag magic_quotes_gpc off
    php_admin_flag allow_url_include off
    php_admin_flag allow_url_fopen off
    php_admin_flag zend.ze1_compatibility_mode off
    php_admin_flag safe_mode Off
    php_admin_value open_basedir "@ap_docroot@/@name@:/var/lib/php5:/tmp:@docdir@/@name@:/etc/@name@"
    # customize suhosin
    php_admin_value suhosin.post.max_array_index_length 256
    php_admin_value suhosin.post.max_totalname_length 8192
    php_admin_value suhosin.post.max_vars 2048
    php_admin_value suhosin.request.max_array_index_length 256
    php_admin_value suhosin.request.max_totalname_length 8192
    php_admin_value suhosin.request.max_vars 2048
  </IfModule>
</Directory>
<Directory @ap_docroot@/@name@/libraries>
  # deny from all
  <IfModule mod_version.c>
    <IfVersion < 2.4>
      Order allow,deny
      Deny from all
    </IfVersion>
    <IfVersion >= 2.4>
      Require all denied
    </IfVersion>
  </IfModule>
  <IfModule !mod_version.c>
    <IfModule !mod_authz_core.c>
      Order allow,deny
      Deny from all
    </IfModule>
    <IfModule mod_authz_core.c>
      Require all denied
    </IfModule>
  </IfModule>
</Directory> 
